apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cert-manager-demo
  region: us-east-1
  version: "1.28"
availabilityZones:
- us-east-1a
- us-east-1b
managedNodeGroups:
- name: mng-general
  labels:
    role: general
  instance-type: t3.small
  desiredCapacity: 2
  minSize: 1
  maxSize: 3
  volumeSize: 20
